---
- name: "Docker Setup"
  hosts: tfvms
  become: yes

  tasks:
    - name: "Install required packages"
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: "Add Docker's official GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Set up the Docker stable repository"
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "$(lsb_release -cs)" stable
        state: present

    - name: "Install Docker CE"
      apt:
        name: docker-ce
        state: present

    - name: "Ensure Docker is running"
      service:
        name: docker
        state: started
        enabled: yes