---
- name: "Docker Setup"
  hosts: tfvms
  become: yes

  tasks:
    - name: "Install Docker"
      apt:
        name: docker.io
        state: present

    - name: "Install Docker Compose"
      apt:
        name: docker-compose
        state: present

    - name: "Start Docker Service"
      service:
        name: docker
        state: started
        enabled: yes